### ISSUE TITLE
Idea: Options for "use" like "ignore".

### ISSUE THREAD

**Issue by h4cc** [nTraum/struct_fields#1]
How about adding options to that use statement?

Like using this to "ignore" some fields that should not be in the `fields` list:

``` elixir
use StructFields, ignore: [:internal_stuff]
```

**Comment by nTraum** [comment]
:+1: Great idea. Not sure if my macro game is strong enough to implement this, so feel free to open up a PR.

**Comment by h4cc** [comment]
Mine neither :) Thats why i created this issue for us both to learn.

**Comment by mpahrens** [comment]
I think `:ignore` is easy, where you can make a base ignore list containing just `:__struct__` and then append to that the passed in ignore opts to using.
`:only, :except` and the rest of the using opts I commonly see don't have as nice of an analogy to manipulating the return value of `__MODULE__.fields` so I don't know if there is a need for that, other than if you had some other criteria for filtering. I am thinking of ideas but they are all value type dependent and would be difficult without a concrete use case.

**Comment by nTraum** [comment]
Ignoring fields has been implemented in #4.
