### ISSUE TITLE
I'm not sure about the implementation

### ISSUE THREAD

**Issue by tallakt** [nTraum/struct_fields#2]
If you would like some (not too diplomatic, I'm sorry) input, I think it would be simpler to put this in a function in a module rather than using macros. Eg:

```
defmodule Struct do
  def fields(struct) do
    for k <- Map.keys(struct), k != :__struct__, do: k
  end
end

# Usage:
# iex> a = %A{}
# iex> Struct.fields(a)
# [:a, :b]
```

**Comment by tallakt** [comment]
On further looking, I see that's not exactly what you are doing. So perhaps ignore this then

**Comment by tallakt** [comment]
Ok, I'll revise that a bit then:

```
defmodule Struct do
  def fields(struct) when is_atom(struct) do
    fields(struct.__struct__)
  end

  def fields(struct) do
    for k <- Map.keys(struct), k != :__struct__, do: k
  end
end

# Usage:
# iex> a = %A{}
# iex> Struct.fields(a)
# [:a, :b]
# iex> Struct.fields(A)
# [:a, :b]
```

**Comment by nTraum** [comment]
I'm not too sure about the implementation either.

I decided against using a function because I want this `fields` to work in multiple structs.
On the other hand, the Elixir docs say:

> Finally, developers should also avoid defining functions inside the `__using__` callback, unless those functions are the default implementation of a previously defined `@callback`. In case you want to provide some existing functionality to the user module, please define it a module which will be imported accordingly.

http://elixir-lang.org/docs/stable/elixir/Kernel.html#use/2

**Comment by nTraum** [comment]
Yes, this indeed looks better and we could get rid of the macro completely. Would you mind if this lib uses your version?

Thanks for your input! :tada:

**Comment by tallakt** [comment]
Sure, use what you like, any licence for all future :) thanks for asking. I was actually surprised that this was not in elixir already. You might want to think about using Struct as a name, perhaps it could be used in core Elixir in the future
